### PR TITLE
Update usage-advanced.md

### PR DESCRIPTION
**Pull request by EricCrosson**
fix typographical error

### CODE REVIEW

**Comment by EricCrosson** [comment]
Hi there, neat project! I was going through the docs and I hope I've found a typo, otherwise I'm more confused than I thought! :)

**Comment by EricCrosson** [comment]
Also now that I think about it, I'm unsure where the 127 (second argument) goes/is used -- it may be an artifact as well

**Comment by andywer** [comment]
Thanks, @EricCrosson! Yeah, this is a severe case of copy & paste gone wrong...

It should actually be
```
expose(function xorBuffer(buffer, value) {
```

Can you please update? I don’t seem to be able to edit files in this PR.

Good catch! 👍

**Comment by EricCrosson** [comment]
Sure I gotcha, thanks for confirming I'm on the right track!

**Comment by EricCrosson** [comment]
Hopefully we can squash these commits during the merge, else let me know and I'll actually clone the project to disk, squash and submit a single rebased commit for your history

**Comment by andywer** [comment]
Done 👍

**Pull request merged**
