### PR TITLE
Update pool.js

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by andywer** [comment]
Nice. I once had that on my to-do list...
But we will have to do it slightly differently, so it won't break the browser version.

**Comment by andywer** [comment]
Is there any special reason why you want the pool to spawn (cpus().length + 1) threads? One thread per core would be more intuitive.

**Comment by andywer** [comment]
I have coded something in the develop branch. Please have a look at it and tell me if it works for you ;)

**Comment by jacobp100** [comment]
Work on that branch looks great! `length + 1` was a typo.

**Comment by andywer** [comment]
New version is 0.5.1. Enjoy and thanks for your contributions.

Let me know if you have further suggestions. New input is always appreciated!

**Pull request merged**
