### PR TITLE
Allow threads.js to function even with webpack node externals

### PR DESCRIPTION
**Pull request by chingyawhao**
Solving https://github.com/andywer/threads.js/issues/222

### CODE REVIEW

**Comment by chingyawhao** [comment]
@andywer this would handle the absolute path returned by `rebaseScriptPath()` that you mentioned right?
I am assuming the absolute path you are talking about is something like `/Users/chingyawhao/Documents`

**Comment by andywer** [comment]
Cool! Pushed a commit introducing some minor code improvements. Yes, that was the absolute path that I meant – only replaced the check with `path.isAbsolute()`, so we can be sure it works with Windows paths, too.

That's some great stuff right here 🙂

**Comment by chingyawhao** [comment]
Thanks @andywer 

I have no idea how to do testing for this scenario though, I tried adding `webpack-node-externals` to the existing node test before these changes but it did not fail

**Comment by andywer** [comment]
@chingyawhao Yeah, I was thinking the same. Unfortunately I don't really have time to look into this right now either…

We should probably just merge the fix. Do you need it urgently, btw?

**Comment by chingyawhao** [comment]
I'm able to make the changes inside node_modules so its no rush

**Pull request merged**
