### PR TITLE
Implement and document `pool.settled()`

### LINKED ISSUE #208: Support allSettled like functionality with pool.completed
It seems to me that `pool.completed()` resolves on the first errored task ([here](https://github.com/andywer/threads.js/blob/12a43f37f0/src/master/pool.ts#L258)). Is it possible to treat it like `Promise.allSettled` and let all the tasks finish regardless of error?

### PR DESCRIPTION
**Pull request by andywer**
Closes #208.

### CODE REVIEW

**Comment by kellyselden** [comment]
Wow what a fast turnaround! This seems great to me.

**Comment by andywer** [comment]
Couldn't sleep last night… 😅

**Comment by andywer** [comment]
Published as v1.2.0 🚀

**Comment by kellyselden** [comment]
Thanks again!

**Pull request merged**
