### PR TITLE
Add CORSWorkaround option + update isAbsoluteURL

### LINKED ISSUE #284: Refused to create a worker
I am trying to run threads in an Atom package (an electron app), but this is the error I am getting when I try to implement a simple example:

The code is here: https://github.com/aminya/ide-json/tree/master/lib

Errors:
Web worker implementation:
```js
C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38 Refused to create a worker from 'blob:file:///844dc93f-470b-4d1e-a82f-2ec4c5d8d087' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

WebWorker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217
C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38 Uncaught (in promise) DOMException: Failed to construct 'Worker': Access to the script at 'blob:file:///844dc93f-470b-4d1e-a82f-2ec4c5d8d087' is denied by the document's Content Security Policy.
    at new WebWorker (C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38:13)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:11:42
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at new Promise (<anonymous>)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:18)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:24)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:147498)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.49.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3308425)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296409)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296187
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3293797)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296047
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3295990)
    at PackageManager.activatePackage (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382943)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382559
    at Config.transactAsync (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:332207)
    at PackageManager.activatePackages (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382509)
    at PackageManager.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382059)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:757178
WebWorker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.browser.js:38
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217

```

Node implementation:
```js
internal/worker.js:100 Uncaught (in promise) Error: The V8 platform used by this instance of Node does not support creating Workers
    at new Worker (internal/worker.js:100:21)
    at new Worker (C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.node.js:111:17)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:11:42
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at new Promise (<anonymous>)
    at file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:15:2
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:18)
    at Object.<anonymous> (file:///C:/Users/yahyaaba/Documents/GitHub/JavaScript/@atom/ide-json/lib/main.js:17:24)
    at Module.get_Module._compile (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:147498)
    at Object.value [as .js] (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/yahyaaba/AppData/Local/atom/app-1.49.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:1:735013)
    at Package.requireMainModule (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3308425)
    at Package.activateNow (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296409)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296187
    at Package.measure (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3293797)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3296047
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:3295990)
    at PackageManager.activatePackage (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382943)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382559
    at Config.transactAsync (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:332207)
    at PackageManager.activatePackages (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382509)
    at PackageManager.activate (C:\Users\yahyaaba\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:382059)
Worker @ internal/worker.js:100
Worker @ C:\Users\yahyaaba\myproject\node_modules\threads\dist\master\implementation.node.js:111
(anonymous) @ main.js:11
step @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:15
(anonymous) @ main.js:17
(anonymous) @ main.js:17
get_Module._compile @ <embedded>:11
value @ <embedded>:11
Module.load @ internal/modules/cjs/loader.js:701
tryModuleLoad @ internal/modules/cjs/loader.js:633
Module._load @ internal/modules/cjs/loader.js:625
Module.require @ index.js:72
require @ internal/modules/cjs/helpers.js:14
customRequire @ <embedded>:1
requireMainModule @ <embedded>:11
activateNow @ <embedded>:11
(anonymous) @ <embedded>:11
measure @ <embedded>:11
(anonymous) @ <embedded>:11
activate @ <embedded>:11
activatePackage @ <embedded>:11
(anonymous) @ <embedded>:11
transactAsync @ <embedded>:11
activatePackages @ <embedded>:11
activate @ <embedded>:11
(anonymous) @ <embedded>:1
async function (async)
(anonymous) @ <embedded>:1
Promise.then (async)
startEditorWindow @ <embedded>:1
t.exports @ <embedded>:1
setupWindow @ index.js:175
window.onload @ index.js:106
load (async)
(anonymous) @ index.js:23
(anonymous) @ index.js:217

```

### PR DESCRIPTION
**Pull request by aminya**
Fixes #284
Closes #286

### CODE REVIEW

**Comment by aminya** [comment]
The error that I got in #284 is now changed to this:
```js
worker.js:1 Uncaught ReferenceError: require is not defined
    at worker.js:1
(anonymous) @ worker.js:1
```

I think now the worker is working properly, but the code is written in a Node fashion. Now I think it is a matter of testing this on another version of Atom. I noticed that Electron needs some options for enabling Node workers (probably unrelated to WebWoker):
https://www.electronjs.org/docs/tutorial/multithreading

**Comment by andywer** [comment]
Looking good, but we can't just drop the CORS fix like that.

Can you try reverting this change here and instead change the regex to this?

```js
/^(blob:|file:|https?:)?\/\//i
```

**Comment by aminya** [comment]
Yes, I can do that!

**Comment by aminya** [comment]
@andywer This is done now!

**Comment by aminya** [comment]
I reverted the commit but the error is back! Are you sure that we need the cors protection in the second condition?

image

**Comment by andywer** [comment]
Yeah, we need that. But maybe this little change could already straighten things (in the WebWorker constructor)?

```diff
-  }
-  if (typeof url === "string" && isAbsoluteURL(url)) {
+  } else if (typeof url === "string" && isAbsoluteURL(url)) {
```

I don't have any time today, but maybe that helps already :)

**Comment by aminya** [comment]
> Yeah, we need that. But maybe this little change could already straighten things (in the WebWorker constructor)?
> 
> ```diff
> -  }
> -  if (typeof url === "string" && isAbsoluteURL(url)) {
> +  } else if (typeof url === "string" && isAbsoluteURL(url)) {
> ```
> 
> I don't have any time today, but maybe that helps already :)

This does not fix the issue. The code does not enter this condition at all. The problem happens in the second branch of `if`. This the compiled code. It goes inside the second branch
```js
    class WebWorker extends Worker {
        constructor(url, options) {
            if (typeof url === "string" && options && options._baseURL) {
                url = new URL(url, options._baseURL);
            }
            else if (typeof url === "string" && !isAbsoluteURL(url) && get_bundle_url_browser_1.getBundleURL().match(/^file:\/\//i)) {


                console.log("comes here")

                url = new URL(url, get_bundle_url_browser_1.getBundleURL().replace(/\/[^\/]+$/, "/"));

				// do we need this??
                url = createSourceBlobURL(`importScripts(${JSON.stringify(url)});`);
            }
            if (typeof url === "string" && isAbsoluteURL(url)) {
                // Create source code blob loading JS file via `importScripts()`
                // to circumvent worker CORS restrictions
                url = createSourceBlobURL(`importScripts(${JSON.stringify(url)});`);
            }
            super(url, options);
        }
    }
```

**Comment by andywer** [comment]
Ahhh, you know what? I think we need to fix the `isAbsoluteURL` function like this:

```diff
- const isAbsoluteURL = (value: string) => /^(file|https?:)?\/\//i.test(value)
+ const isAbsoluteURL = (value: string) => /^(file:|https?:)?\/\//i.test(value) || /^blob:/.test(value)
```

As the `blob:` URL we see does not come with double slashes…

**Comment by andywer** [comment]
@aminya Any news?

**Comment by aminya** [comment]
@andywer no difference: 

```js
C:\Users\aminy\Docum…ation.browser.js:40 Refused to create a worker from 'blob:file:///6be44486-60a8-4fa6-9cf6-0b0137592712' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

```

**Comment by andywer** [comment]
> As I said the problem is this line:

Sure, but it should not execute that line in the first place as the condition for that `else if` branch contains `!isAbsoluteURL(url)` and I would say a blob URL qualifies as absolute URL…

So weird.

**Comment by aminya** [comment]
@andywer But the input `url` is `./worker.js`. It is not an absolute URL, so it goes inside the second condition.

**Comment by andywer** [comment]
Ahhh, that happens when you don't run the code yourself… Of course, you are right!

> Why not use a package like https://www.npmjs.com/package/is-absolute-url, which covers all the possibilities.

Could do, but I also try to find a balance where we don't rely on too many dependencies. So for these classic one-liners I try to avoid introducing additional deps. But yeah, maybe those one-liners should be based more closely on existing code 😉

> C:\Users\aminy\Docum…ation.browser.js:40 Refused to create a worker from 'blob:file:///6be44486-60a8-4fa6-9cf6-0b0137592712' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

What is your Content Security Policy, btw?

We have been using this CSP in an Electron/Cordova app:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; child-src 'self' blob: file://*; connect-src *; img-src *; script-src 'self' blob: file://*; style-src 'self' 'unsafe-inline'; worker-src 'self' blob: file://*;">
```

**Comment by aminya** [comment]
> Ahhh, that happens when you don't run the code yourself… Of course, you are right!
> 
> > Why not use a package like [npmjs.com/package/is-absolute-url](https://www.npmjs.com/package/is-absolute-url), which covers all the possibilities.
> 
> Could do, but I also try to find a balance where we don't rely on too many dependencies. So for these classic one-liners I try to avoid introducing additional deps. But yeah, maybe those one-liners should be based more closely on existing code 😉
> 

So what is the solution now? Should we use a better is-absolute-url function?

> 
> What is your Content Security Policy, btw?
> 
> We have been using this CSP in an Electron/Cordova app:
> 
> ```
> <meta http-equiv="Content-Security-Policy" content="default-src 'self'; child-src 'self' blob: file://*; connect-src *; img-src *; script-src 'self' blob: file://*; style-src 'self' 'unsafe-inline'; worker-src 'self' blob: file://*;">
> ```

Atom's CSP is this:
https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/static/index.html#L4

**Comment by andywer** [comment]
Let's improve the function we have, so that it matches `/^[A-Za-z0-9]+:/` and `/^\/\//`. But as you pointed out, that won't fix the issue.

I take it you are working with Atom and cannot change the CSP? 🙈

So if the code works when [this line of code](https://github.com/andywer/threads.js/pull/287#issuecomment-673876742) is not run, then let's just add an option to opt-out of the CORS workaround.

**Comment by aminya** [comment]
@andywer I added the option. Should it be documented anywhere? I don't know where to add the docs.

**Comment by aminya** [comment]
This is ready to go too.

**Comment by andywer** [comment]
Great stuff! 👍 

> Should it be documented anywhere?

Maybe, but as it's quite specific and hopefully not going to be needed too often, I think we can live with only documenting the code inline (also shown in IntelliSense) for now.

**Pull request merged**
