### PR TITLE
Compat with electron

### PR DESCRIPTION
**Pull request by jacobp100**

### CODE REVIEW

**Comment by andywer** [comment]
I will fix the build this evening.

**Comment by jacobp100** [comment]
Just a note that would need to be documented (possibly fixed somewhere in the code too), inElectron, `__dirname` is the url. All paths are resolved from the root directory, so if you have a dist directory, you need to configure `{ basepath: { node: './dist' } }`

**Comment by andywer** [comment]
Good point. The only place where `__dirname` is used is in the node worker. Can you check if it's working for you as it is? I guess you need to be able to set the path to the slave.js file manually.

**Comment by jacobp100** [comment]
It does work as-is for me. The workers I need to call are at the root level, and to call them from within a file within I run `spawn('./worker')` regardless of whether the file is at the root level.

**Comment by andywer** [comment]
But can you run a function in a worker like `spawn((input, done) => { done(); })`? I guess that would fail on Electron.

**Comment by jacobp100** [comment]
No, that works.

**Comment by andywer** [comment]
Nice. That fix might be worth to become version 0.5.2.

**Pull request merged**
