### PR TITLE
Test and build in separate jobs

### PR DESCRIPTION
**Pull request by aminya**
This allows using the latest tools for building on the latest Node.js while supporting older versions for running the code

Fixes the errors in #349

### CODE REVIEW

**Comment by aminya** [comment]
This is ready now

**Comment by andywer** [comment]
Cool, great idea!

I'm just wondering why the `test/` directory has been renamed to `test-dev/` and what's the story behind the two npm test scripts? 😉

**Comment by aminya** [comment]
Thanks!

I separated the runtime tests from dev time tests. Dev time tests (such as bundling with Webpack and Rollup) are tested on the latest Node, and all the other tests are tested on old Node. This allows us to use the latest tools while keeping backward compatibility for old runtimes.

**Comment by andywer** [comment]
Sounds reasonable. My only issue is that the npm script names failed to convey their purpose to me…

How about `test:library` & `test:tooling` instead? Or maybe `test:integration` for the latter. WDYT?

Don't want to unnecessarily delay the merge, but since we cannot add comments to the package.json, we should pay a bit of extra attention to the naming there 🙂

**Comment by aminya** [comment]
> Sounds reasonable. My only issue is that the npm script names failed to convey their purpose to me…
> 
> How about `test:library` & `test:tooling` instead? Or maybe `test:integration` for the latter. WDYT?
> 
> Don't want to unnecessarily delay the merge, but since we cannot add comments to the package.json, we should pay a bit of extra attention to the naming there 🙂

Sure, that sounds good to me.

**Pull request merged**
